# Homework 2 - balancing, transformations, and dimensionality reduction (deadline 21. 12. 2025, 23:59)

In short, the main task is to play with balancing, binning, transformations, and dimensionality reduction to obtain the best results for the binary classification task.
  
> The instructions are not given in detail: It is up to you to come up with ideas on how to fulfill the particular tasks as best you can!

However, we **strongly recommend and require** the following:
* Follow the assignment step by step. Number each step.
* Properly comment on all your steps. Use Markdown cells and visualizations. Comments are evaluated for 2 points of the total, together with the final presentation of the solution. However, it is not desirable to write novels! 
* This task is timewise and computationally intensive. Do not leave it to the last minute.
* Most steps contain the number of features that should be treated. You can preprocess more features. However, it does not mean the teacher will give you more points. Focus on quality, not quantity.
* Hand in a notebook that has already been run (i.e., do not delete outputs before handing in).

## What are you supposed to do:

  1. Download the dataset [here](https://www.dropbox.com/s/aq08ytozfplb97b/data.csv?dl=0). Split the dataset into a train, validation, and test set and **use these parts correctly (!)** in the following steps.
  1. Choose at least one classification algorithm whose performance is to be improved in the following steps.
  1. Use at least two binning methods (on features of your choice, with your choice of parameters) and comment on their effects on classification performance. _I.e., one kind of classifier trained for each binning and a comparison of the effect of binning methods against each other._ _(4 points, depends on creativity)_ 
  1. Use at least two data balancing techniques on the correct part of the dataset and comment on its effects on classification performance. Focus on the comparison of methods between each other. _I.e., one type of classifier trained for each balancing and a comparison of the effect of balancing methods against each other._ **Just copied code from tutorial four will not be accepted.** _(6 points, depends on creativity)_
  1. Transform the features appropriately and prepare new ones (i.e., feature engineering) - focus on the increase in the model's performance (possibly in combination with further steps). _(5 points, depends on creativity)_ 
  1. Try to find some suitable subset of features - use at least two feature selection methods. Evaluate your choice on the validation set and discuss the influence. Do not use PCA (principal component analysis) in this step. Manual selection will not be accepted. _(4 points, depends on creativity)_
  1. Use PCA to reduce the dimensionality. Discuss the influence of the number of principal components. _(4 points)_
  1. Try to find the best combination of the previous steps and run final classification tests on the correct part of the dataset - first for the original data, second for the best-found combination of the previous preprocessing steps. Compare the results and discuss (give a comment, use graphs, and so on). _(5 points)_

All your steps, choices, and the following code **must be commented on!** For text comments (discussion, etc., not code comments), use **Markdown cells**. Comments are evaluated for _2 points_ together with the final presentation of the solution.

**If you do all this properly, you will obtain 30 points.**

### FAQ

* Select the appropriate metric to evaluate the classification results.
* In steps 2 and 3, you are comparing methods against each other, not their effect on unadjusted data. However, you can comment on that, too.
* You choose the subset of features only in step 2 because of the binning methods. In the other steps, you work with the whole dataset.

## Comments

  * Please follow the technical instructions from https://courses.fit.cvut.cz/NI-PDD/homeworks/index.html.
  * Methods that are more complex and were not shown during the tutorials are considered more creative and should be described in detail.
  * English is not compulsory.

  
## Data description

* The dataset can be downloaded [here](https://www.dropbox.com/s/aq08ytozfplb97b/data.csv?dl=0).
* The data are devoted to the binary classification task. The aim is to predict the probability that a driver will initiate an auto insurance claim next year.
* The target feature is called 'y' and signifies whether or not a claim was filed for that policyholder.
* To fulfill the task, one does not need to know the meaning of predictors.
* Predictors that belong to similar groupings are tagged as such in the feature names (e.g., ind, reg, car, calc). In addition, feature names include the postfix _bin_ to indicate binary features and the postfix _cat_ to indicate categorical features. Features without these designations are either continuous or ordinal. Values of -1 indicate that the feature was missing from the observation.
* While using [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html), control the shuffling of data by random_state parameter. Do not use shuffle=False, probably never (can cause systematic error).

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer

In [2]:
### here comes your code
df = pd.read_csv("data.csv")

X = df.drop('y', axis=1)
y = df['y']

df.head(10)

,y,xind_01,xind_02_cat,xind_03,xind_04_cat,xind_05_cat,xind_06_bin,xind_07_bin,xind_08_bin,xind_09_bin,...,xcalc_11,xcalc_12,xcalc_13,xcalc_14,xcalc_15_bin,xcalc_16_bin,xcalc_17_bin,xcalc_18_bin,xcalc_19_bin,xcalc_20_bin
0,0,2,1,5,1,6,0,1,0,0,...,4,0,2,8,0,0,0,1,1,0
1,0,2,1,6,0,0,0,0,0,1,...,9,2,3,7,0,0,1,0,0,0
2,0,2,1,9,0,0,1,0,0,0,...,5,0,2,6,0,1,0,1,1,0
3,0,1,1,6,0,0,1,0,0,0,...,3,0,4,8,0,0,1,0,0,0
4,0,1,1,5,1,0,0,1,0,0,...,4,3,1,2,0,1,0,0,1,0
5,0,1,1,2,1,0,0,1,0,0,...,9,2,3,5,0,0,1,0,0,0
6,0,2,1,3,0,0,0,0,0,1,...,8,4,1,6,1,1,0,0,0,0
7,0,2,1,3,1,0,0,1,0,0,...,8,1,3,7,0,1,1,0,1,0
8,0,0,2,1,0,0,1,0,0,0,...,5,3,2,6,0,1,0,0,0,0
9,0,5,1,2,1,0,0,1,0,0,...,6,0,3,8,0,1,1,0,1,0

In [3]:
df.shape

(595212, 58)

In [4]:
X_temp, X_test, y_temp, y_test = train_test_split(
    X, 
    y, 
    test_size=0.8, 
    random_state=42,
    stratify=y
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, 
    y_temp, 
    test_size=0.25, 
    random_state=42,
    stratify=y_temp
)

In [5]:
# pro logistickou regresi neni dobre nechavat chybeici data na -1, pouziju imputaci na median

def replaceMissingValues(data, median, feature):
    data = data.replace(-1, np.nan).copy()
    data[feature] = data[feature].fillna(median)
    return data
    
X_train_imput = X_train.copy()
X_val_imput = X_val.copy()

for column in X_train_imput.columns:
    X_train_imput[column] = X_train_imput[column].replace(-1, np.nan).copy()
    X_val_imput[column] = X_val_imput[column].replace(-1, np.nan).copy()
        
    median = X_train_imput[column].median()
    X_train_imput = replaceMissingValues(X_train_imput, median, column)
    X_val_imput = replaceMissingValues(X_val_imput, median, column)

model jsem nejprve chtěl použít logistickou regresi, ale ta nepracuje dobře s kategorickými daty, takže bych sloupce musel
buď převest na one hot encoding, což by dataset nafouklo, nebo odstranit. 
Rozhodl jsem se tedy použít klasický strom, který umí pracovat s těmito daty a navíc dobře pracuje, i když jsou NaN reprezentovány pomocí -1.
Zkusim obojí, nechat -1 a i imputaci s medianem

Výslekdy klasickeho DecisionTreeClassifier se mi nelíbili, tak jsem zkusil i random forest.

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RandomizedSearchCV

In [7]:
def best_random_forest(x_data, y_data, x_val_data, y_val_data):
    best_estimators = 5
    best_roc = 0
    best_depth = 3
    
    for estimators in range (5, 400, 50):
        for depth in range (2,6,2):
            RFC_MODEL = RandomForestClassifier(
                n_estimators=estimators,
                max_depth=depth,
                class_weight='balanced',
                n_jobs=-1
            )
            
            RFC_MODEL.fit(x_data, y_data)
            y_val_proba_rfc = RFC_MODEL.predict_proba(x_val_data)[:, 1]
            roc_auc_rfc = roc_auc_score(y_val_data, y_val_proba_rfc)
    
    
            if roc_auc_rfc > best_roc:
                best_roc = roc_auc_rfc
                best_estimators = estimators
                best_depth = depth
    
            
    RFC_MODEL = RandomForestClassifier(
        n_estimators=best_estimators,
        max_depth=best_depth,
        class_weight='balanced',
        n_jobs=-1
    )
    
    RFC_MODEL.fit(x_data, y_data)
    y_val_proba_rfc = RFC_MODEL.predict_proba(x_val_data)[:, 1]
    roc_auc_rfc = roc_auc_score(y_val_data, y_val_proba_rfc)
    
    print(roc_auc_rfc)
    return RFC_MODEL

In [8]:
best_random_forest(X_train_imput, y_train, X_val_imput, y_val)

0.6184091708218886

RandomForestClassifier(class_weight='balanced', max_depth=4, n_estimators=305,
                       n_jobs=-1)

In [9]:

def best_decision_tree(x_data, y_data, x_val_data, y_val_data):
    max_roc = 0
    best_depth = 0
    
    for depth in range(1,10,2):
        DTC_MODEL = DecisionTreeClassifier(
        max_depth=depth,
        class_weight='balanced'
        )
        DTC_MODEL.fit(x_data, y_data)
        y_val_proba_imput = DTC_MODEL.predict_proba(x_val_data)[:, 1]
        roc_auc_imput_dtc = roc_auc_score(y_val_data, y_val_proba_imput)
        
        if roc_auc_imput_dtc > max_roc:
            best_depth = depth
            max_roc = roc_auc_imput_dtc
    
    DTC_MODEL = DecisionTreeClassifier(
        max_depth=best_depth,
        class_weight='balanced'
    )
    DTC_MODEL.fit(x_data, y_data)
    y_val_proba_imput = DTC_MODEL.predict_proba(x_val_data)[:, 1]
    roc_auc_imput_dtc = roc_auc_score(y_val_data, y_val_proba_imput)
    print(roc_auc_imput_dtc)

    return DTC_MODEL

In [10]:
best_decision_tree(X_train_imput, y_train, X_val_imput, y_val)

0.596928242631967

DecisionTreeClassifier(class_weight='balanced', max_depth=3)

### 3) binning

In [11]:
# nejprve zkusim binning

In [12]:
# pro logistickou regresi je potreba onehot encoding, pokud jsou data kategoricka neordinalni, nase sloupce jsou ordinalni, takze staci priznak ordinal



bin_uniform = KBinsDiscretizer(
    n_bins=5, 
    encode='ordinal',
    strategy='uniform', 
    subsample=None
)

bin_quantile = KBinsDiscretizer(
    n_bins=5, 
    encode='ordinal',
    strategy='quantile', 
    subsample=None
)

In [13]:
def get_binned(bin_cols, X_data, X_val_data, discretizer_type, bins):
    

    binnarizer = KBinsDiscretizer(
        n_bins=bins, 
        encode='ordinal',
        strategy=discretizer_type, 
        subsample=None
    )
    
    X_train_bin = X_data.copy()
    X_val_bin = X_val_data.copy()


    for column in bin_cols:

        binnarizer.fit(X_train_bin[[column]])

        X_train_binned_data = binnarizer.transform(X_train_bin[[column]])
        X_val_binned_data = binnarizer.transform(X_val_bin[[column]])

        new_column_name = f'{column}_binned_ordinal'

        X_train_bin[new_column_name] = X_train_binned_data[:, 0]
        X_val_bin[new_column_name] = X_val_binned_data[:, 0]

        X_train_bin.drop(columns=[column], inplace=True)
        X_val_bin.drop(columns=[column], inplace=True)

    return X_train_bin, X_val_bin

In [14]:
binning_cols = ["xcalc_13", "xcalc_14"]

X_train_BINNED, X_val_BINNED = get_binned(binning_cols, X_train_imput, X_val_imput, 'quantile', 6)

/home/mara/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_discretization.py:322: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(

In [15]:
X_train_BINNED.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89281 entries, 509234 to 337661
Data columns (total 57 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   xind_01                  89281 non-null  int64
 1   xind_02_cat              89281 non-null  float64
 2   xind_03                  89281 non-null  int64
 3   xind_04_cat              89281 non-null  float64
 4   xind_05_cat              89281 non-null  float64
 5   xind_06_bin              89281 non-null  int64
 6   xind_07_bin              89281 non-null  int64
 7   xind_08_bin              89281 non-null  int64
 8   xind_09_bin              89281 non-null  int64
 9   xind_10_bin              89281 non-null  int64
 10  xind_11_bin              89281 non-null  int64
 11  xind_12_bin              89281 non-null  int64
 12  xind_13_bin              89281 non-null  int64
 13  xind_14                  89281 non-null  int64
 14  xind_15                  89281 non-null  int64
 15  xind_16_bin              89281 non-null  int64
 16  xind_17_bin              89281 non-null  int64
 17  xind_18_bin              89281 non-null  int64
 18  xreg_01                  89281 non-null  float64
 19  xreg_02                  89281 non-null  float64
 20  xreg_03                  89281 non-null  float64
 21  xcar_01_cat              89281 non-null  float64
 22  xcar_02_cat              89281 non-null  float64
 23  xcar_03_cat              89281 non-null  float64
 24  xcar_04_cat              89281 non-null  int64
 25  xcar_05_cat              89281 non-null  float64
 26  xcar_06_cat              89281 non-null  int64
 27  xcar_07_cat              89281 non-null  float64
 28  xcar_08_cat              89281 non-null  int64
 29  xcar_09_cat              89281 non-null  float64
 30  xcar_10_cat              89281 non-null  int64
 31  xcar_11_cat              89281 non-null  int64
 32  xcar_11                  89281 non-null  int64
 33  xcar_12                  89281 non-null  float64
 34  xcar_13                  89281 non-null  float64
 35  xcar_14                  89281 non-null  float64
 36  xcar_15                  89281 non-null  float64
 37  xcalc_01                 89281 non-null  float64
 38  xcalc_02                 89281 non-null  float64
 39  xcalc_03                 89281 non-null  float64
 40  xcalc_04                 89281 non-null  int64
 41  xcalc_05                 89281 non-null  int64
 42  xcalc_06                 89281 non-null  int64
 43  xcalc_07                 89281 non-null  int64
 44  xcalc_08                 89281 non-null  int64
 45  xcalc_09                 89281 non-null  int64
 46  xcalc_10                 89281 non-null  int64
 47  xcalc_11                 89281 non-null  int64
 48  xcalc_12                 89281 non-null  int64
 49  xcalc_15_bin             89281 non-null  int64
 50  xcalc_16_bin             89281 non-null  int64
 51  xcalc_17_bin             89281 non-null  int64
 52  xcalc_18_bin             89281 non-null  int64
 53  xcalc_19_bin             89281 non-null  int64
 54  xcalc_20_bin             89281 non-null  int64
 55  xcalc_13_binned_ordinal  89281 non-null  float64
 56  xcalc_14_binned_ordinal  89281 non-null  float64
dtypes: float64(21), int64(36)
memory usage: 39.5 MB

In [16]:
X_train_BINNED["xcalc_13_binned_ordinal"].unique()

array([4., 2., 0., 1., 3.])

In [17]:
best_random_forest(X_train_BINNED, y_train, X_val_BINNED, y_val)

0.617679004520873

RandomForestClassifier(class_weight='balanced', max_depth=4, n_estimators=305,
                       n_jobs=-1)

In [18]:
best_decision_tree(X_train_BINNED, y_train, X_val_BINNED, y_val)

0.596928242631967

DecisionTreeClassifier(class_weight='balanced', max_depth=3)

TODO - experimentovat s poctem sloupcu v binningu a taky s tim, jaky binning pouziju

### 4) data balancing

In [19]:

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

In [20]:
y_train.value_counts()

y
0    86027
1     3254
Name: count, dtype: int64

In [21]:
sm = SMOTE(random_state=42)
X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train_BINNED, y_train)

In [22]:
y_train_SMOTE.value_counts()

y
0    86027
1    86027
Name: count, dtype: int64

In [23]:
rus = RandomUnderSampler(random_state=42)
X_train_RUS, y_train_RUS = rus.fit_resample(X_train_BINNED, y_train)

In [24]:
y_train_RUS.value_counts()

y
0    3254
1    3254
Name: count, dtype: int64

TODO - vic experimentovat a okomentovat

In [25]:
best_decision_tree(X_train_RUS, y_train_RUS, X_val_BINNED, y_val)
best_decision_tree(X_train_SMOTE, y_train_SMOTE, X_val_BINNED, y_val)

0.5777920070606097
0.5508786872305427

DecisionTreeClassifier(class_weight='balanced', max_depth=5)

In [26]:
best_random_forest(X_train_RUS, y_train_RUS, X_val_BINNED, y_val)
best_random_forest(X_train_SMOTE, y_train_SMOTE, X_val_BINNED, y_val)

0.614395795260315
0.5602047152582837

RandomForestClassifier(class_weight='balanced', max_depth=2, n_estimators=355,
                       n_jobs=-1)

### 5) finding best model

In [27]:
# TODO

### 6) feature selection

Zkusim jednu filtrovou metodu, vyberu si výběr dle variance, protože používám stromy a to jsou nelineární modely. Korelaci a t-test mohu taky vyzkoušet, ale očekávám, že pro nelineární model bude variance nejlepší.

metoda variance i korelace se da pouzit pro ordinalni i kategoricka data

In [28]:
# VARIANCE
variances = X_train_BINNED.var()
low_variance_features = variances[variances < 0.01]
low_variance_features = low_variance_features.sort_values(ascending = True)
low_variance_features

xind_10_bin    0.000381
xind_13_bin    0.000985
xind_11_bin    0.001510
xcar_14        0.001944
xcar_12        0.003401
xcar_10_cat    0.008492
xind_12_bin    0.009309
dtype: float64

In [29]:
# KORELACE - SPEARMAN
correlation_with_y = X_train_BINNED.apply(lambda x: x.corr(y_train, method='spearman'))
sorted_correlation = correlation_with_y.reindex(correlation_with_y.abs().sort_values(ascending=False).index)
low_correlation_features = sorted_correlation[(sorted_correlation < 0.001) &  (sorted_correlation > -0.001)]
low_correlation_features = low_correlation_features.sort_values(key=abs,ascending=True)
low_correlation_features

xind_11_bin                0.000123
xcalc_05                   0.000277
xcalc_01                  -0.000546
xcalc_06                   0.000587
xcalc_13_binned_ordinal    0.000607
xcalc_16_bin               0.000729
xcalc_09                  -0.000741
xcalc_18_bin               0.000801
xcalc_11                  -0.000898
xcalc_12                  -0.000929
dtype: float64

sklearn ma naimplementované různé funkce, zkusím použít KBest s chi-kvadrat rozdelenim pro kategoricka data

In [30]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFECV
from sklearn.preprocessing import StandardScaler

In [31]:
categorical_binary_cols = [col for col in X_train_BINNED.columns 
                           if ('_cat' in col or '_bin' in col) and ('_binned' not in col)]
X_train_chi2_data = X_train_BINNED[categorical_binary_cols]

selector_chi2 = SelectKBest(score_func=chi2, k=30)
selector_chi2.fit(X_train_chi2_data, y_train)
chi2_scores = selector_chi2.scores_
chi2_results = pd.Series(chi2_scores, index=X_train_chi2_data.columns)
low_chi_features = chi2_results.sort_values(ascending=True)
low_chi_features = low_chi_features[0:10]
low_chi_features

xind_11_bin     0.001340
xcar_10_cat     0.003379
xcalc_16_bin    0.017766
xcalc_18_bin    0.040859
xcalc_17_bin    0.216093
xcalc_15_bin    0.453433
xcar_03_cat     0.695092
xcar_07_cat     0.739258
xcalc_19_bin    0.860533
xind_13_bin     1.039903
dtype: float64

RCEFV

In [32]:
# lr je rychla, je sice potreba naskalovat ale jako rekurzivni wrapper metoda je velmi robustni

lr_estimator = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    class_weight='balanced',
    random_state=42
)

rfecv_selector = RFECV(
    estimator=lr_estimator,
    step=5, 
    cv=3,
    scoring='roc_auc', 
    n_jobs=-1
)
X_train_SCALED = StandardScaler().fit_transform(X_train_BINNED)
rfecv_selector.fit(X_train_SCALED, y_train)

RFECV(cv=3,
      estimator=LogisticRegression(class_weight='balanced', penalty='l1',
                                   random_state=42, solver='liblinear'),
      n_jobs=-1, scoring='roc_auc', step=5)

In [33]:
optimal_features = X_train_BINNED.columns[rfecv_selector.support_]
optimal_features

Index(['xind_01', 'xind_02_cat', 'xind_03', 'xind_04_cat', 'xind_05_cat',
       'xind_07_bin', 'xind_08_bin', 'xind_09_bin', 'xind_10_bin', 'xind_15',
       'xind_16_bin', 'xind_17_bin', 'xreg_01', 'xreg_02', 'xreg_03',
       'xcar_05_cat', 'xcar_06_cat', 'xcar_07_cat', 'xcar_09_cat',
       'xcar_11_cat', 'xcar_12', 'xcar_13', 'xcar_14', 'xcar_15', 'xcalc_03',
       'xcalc_06', 'xcalc_08', 'xcalc_10', 'xcalc_17_bin', 'xcalc_19_bin',
       'xcalc_20_bin', 'xcalc_14_binned_ordinal'],
      dtype='object')

### 7) PCA

In [35]:
# cviko 5
from sklearn.decomposition import PCA

pro PCA nemuzou byt data nenaskalovana a nemuzou zde byt kategoricka data

budu pca delat jen pro nekategoricke sloupce, dal by se udelat one-hot encoding, ale to by hodne nafouklo dataset,
lze to ale vyzkouset

In [54]:
def getPCAValues(X_Train, X_Val, components):
    # ziskani nekategorickych sloupcu
    pca_cols = [col for col in X_Train.columns if col not in categorical_binary_cols]
    X_train_PCA_input = X_Train[pca_cols].copy()
    X_val_PCA_input = X_Val[pca_cols].copy()
    
    # skalovani nutne pro PCA
    scaler = StandardScaler()
    X_train_PCA_input = scaler.fit_transform(X_train_PCA_input)
    X_val_PCA_input = scaler.transform(X_val_PCA_input)

    
    # definice a trenink PCA
    pca = PCA(n_components=components, random_state=37)

    pca.fit(X_train_PCA_input)

    X_train_pca = pca.transform(X_train_PCA_input)
    X_val_pca = pca.transform(X_val_PCA_input)

    # rekonstrukce datasetu
    pca_component_names = [f'PCA_C_{i}' for i in range(1, pca.n_components_ + 1)]
    X_train_pca_df = pd.DataFrame(X_train_pca, columns=pca_component_names, index=X_Train.index)
    X_val_pca_df = pd.DataFrame(X_val_pca, columns=pca_component_names, index=X_Val.index)
   
    X_train_discrete = X_Train[categorical_binary_cols]
    X_val_discrete = X_Val[categorical_binary_cols]

    X_train_FINAL_PCA = pd.concat([X_train_pca_df, X_train_discrete], axis=1)
    X_val_FINAL_PCA = pd.concat([X_val_pca_df, X_val_discrete], axis=1)
    
    return X_train_FINAL_PCA, X_val_FINAL_PCA

In [55]:
X_train_PCA, X_val_PCA = getPCAValues(X_train_BINNED, X_val_BINNED, 0.95)

In [58]:
X_val_PCA.shape

(29761, 54)

In [60]:
X_train_BINNED.shape

(89281, 57)

In [61]:
X_train_PCA.head()

,PCA_C_1,PCA_C_2,PCA_C_3,PCA_C_4,PCA_C_5,PCA_C_6,PCA_C_7,PCA_C_8,PCA_C_9,PCA_C_10,...,xcar_08_cat,xcar_09_cat,xcar_10_cat,xcar_11_cat,xcalc_15_bin,xcalc_16_bin,xcalc_17_bin,xcalc_18_bin,xcalc_19_bin,xcalc_20_bin
509234,1.952257,-1.644346,-1.427593,-0.537112,0.738968,-1.108785,0.657323,0.055405,-1.454849,-0.051713,...,1,0.0,1,50,0,1,1,0,0,0
301078,2.988104,3.906875,-1.576955,0.817466,-1.062674,0.619609,-0.026162,1.313526,1.759033,0.905467,...,1,0.0,1,4,0,1,1,0,1,0
229914,-1.308144,-1.622905,-1.534832,1.141153,-0.361076,0.256371,-0.580733,-0.261724,-1.154401,0.645093,...,1,2.0,1,64,0,1,0,0,0,0
130398,-0.461327,1.127256,-0.049226,0.360651,1.319273,1.354455,0.110718,0.712512,1.118471,-0.619100,...,1,2.0,1,104,0,1,1,1,0,0
5993,-1.394314,0.492794,-0.642055,-2.001911,-0.371415,0.084782,2.308883,-0.344943,-0.660228,1.064054,...,1,2.0,1,87,0,1,1,1,1,0

### 8) best model